### ISSUE TITLE
no account for team "97NU232GB7"等三个报错

### ISSUE THREAD

**Issue by mrj666** [lexiaoyao20/Outline_iOS_Client#2]
<img width="709" alt="2018-12-21 11 00 10" src="https://user-images.githubusercontent.com/33885009/50348904-1a2d4e00-0575-11e9-95e1-eede9f7a3f1e.png">

**Comment by lexiaoyao20** [comment]
这个需要你改成你自己的开发者账号，而且BundleId也需要改成和我这边不一样的，因为苹果那边规定每个产品的BundleId都是唯一的
